-- 0048_visa_overrides.sql
-- 비자 서류 편집분(overrides)을 공유 DB로 이전 — 비자앱 편집 → 유학센터(/center/visa) 라이브 반영.
--   base(rules 등)는 코드에 있고, 편집분만 여기 저장. lang 별 1행(경로→값 JSON).
--   시드 = 현재 커밋된 overrides(.json/.vi.json) 그대로 → 이전 시점의 표시가 그대로 유지됨.

create table if not exists public.study_visa_overrides (
  lang text primary key check (lang in ('ko','vi')),
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.study_visa_overrides enable row level security;
-- 읽기: 로그인 사용자(유학센터·학생). 쓰기 정책 없음 → service_role(비자앱 저장 라우트)만 기록 가능.
drop policy if exists svo_read on public.study_visa_overrides;
create policy svo_read on public.study_visa_overrides
  for select to authenticated using (true);

-- 시드(현재 편집분). 이미 있으면 덮어쓰지 않음(운영 편집 보존).
insert into public.study_visa_overrides (lang, data) values
  ('ko', '{
  "doc:passport:detailDesc": "여권 발급 절차를 잘 숙지하여 미리 준비해주세요.",
  "doc:passport:brief": "본국 여권",
  "doc:passport:obtainDays": "공안부 출입국관리소: 5일 / 지방 경찰 출입국관리소: 8일",
  "doc:passport:issuer": "공안부/지방 경찰 출입국관리소",
  "doc:visa-form:detailDesc": "흰 배경 증명사진 3.5×4.5cm 1장(6개월 이내 촬영)이 필요하며, 대사관 홈페이지에서 미리 다운로드 받을 수 있습니다.",
  "doc:visa-form:brief": "비자 신청 시 제출하는 대사관 양식의 문서",
  "doc:visa-form:issuer": "대사관",
  "doc:id-card:brief": "본인 신분증",
  "doc:id-card:name": "신분증",
  "doc:id-card:detailDesc": "정부에서 발급하는 신분증입니다. CCCD (증명서는 사용불가)",
  "doc:id-card:_hidden": "[\"translation\",\"validity\"]",
  "doc:id-card:form": "원본 및 사본",
  "doc:id-card:obtainDays": "7일",
  "doc:id-card:issuer": "공안부 사회질서행정관리경찰국 ",
  "doc:admission:detailDesc": "대학 입학심사 통과 시 발급되며, 대사관 비자 심사 시 제출합니다.",
  "doc:admission:holder": "본인",
  "doc:admission:validity": "3개월",
  "doc:admission:obtainDays": "서류 제출일로부터 1일 ~ 10일",
  "doc:univ-reg:name": "대학 사업자등록증",
  "doc:univ-reg:brief": "대학이 제공하는 대한민국 공식 서류",
  "doc:univ-reg:detailDesc": "대학에 요청하여 받을 수 있으며, 고유번호증으로 대체할 수 있습니다",
  "doc:univ-reg:holder": "대학",
  "doc:univ-reg:issuer": "대한민국 정부",
  "doc:univ-reg:_hidden": "[\"obtainDays\",\"issuer\",\"validity\"]",
  "doc:family-ct07:brief": "거주정보 확인 서류.",
  "doc:family-ct07:issuer": "베트남 공안부",
  "doc:family-ct07:translation": "한글 또는 영어가 아닐 경우 번역 및 공증 필요",
  "doc:family-ct07:obtainDays": "1일 ~ 3일",
  "doc:family-ct07:name": "CT07",
  "doc:family-ct07:detailDesc": "본인의 거주를 확인합니다. ",
  "doc:birth-cert:brief": "부모와의 관계 입증.",
  "doc:birth-cert:detailDesc": "부모님의 국적 및 재정보증인으로써 부보가 맞는지 확인합니다.",
  "doc:birth-cert:form": "번역 및 공증된 원본",
  "doc:birth-cert:translation": "한글 또는 영어가 아닐 경우 번역 및 공증 필요",
  "doc:birth-cert:notarization": "한글 또는 영어가 아닐 경우 번역 및 공증 필요",
  "doc:family-ct07:_extra": "[]",
  "doc:birth-cert:obtainDays": "1일 ~ 10일",
  "doc:family-ct07:form": "번역 및 공증된 원본",
  "doc:residence-ct08:name": "CT08",
  "doc:residence-ct08:brief": "호적과 다른 지역의 대사관/영사관에 비자를 신청할 때 제출",
  "doc:residence-ct08:cond": "",
  "doc:residence-ct08:detailDesc": "호적과 다른 지역 1년 이상 거주 이력(대체: 6개월 근무·재학). 고교 졸업 6개월 이내면 면제.",
  "doc:residence-ct08:translation": "한글 또는 영어가 아닐 경우 번역 및 공증 필요",
  "doc:residence-ct08:_extra": "[]",
  "doc:grad-cert:detailDesc": "고등학교 또는 대학교 서류를 제출합니다. 졸업예정일 1년 이내라면 졸업예정증명서로 대체하여 제출합니다. 대학교 재학 또는 졸업생이더라도 고등학교 서류도 같이 제출하면 좋습니다.",
  "doc:grad-cert:cond": "",
  "doc:grad-cert:issuer": "학교",
  "doc:grad-cert:translation": "한글 또는 영어가 아닐 경우 번역 및 공증 필요",
  "doc:birth-cert:_hidden": "[\"notarization\"]",
  "doc:grad-cert:_extra": "[]",
  "doc:grad-cert:authentication": "필수, 외무성 → 총영사관",
  "doc:transcript:authentication": "필수, 외무성 → 총영사관",
  "doc:grad-cert:obtainDays": "8일 ~ 20일(발급 3 ~ 7일 + 번역 및 공증 1일 ~ 3일 + 영사확인 4 ~ 8일)  ",
  "doc:transcript:obtainDays": "8일 ~ 20일(발급 3 ~ 7일 + 번역 및 공증 1일 ~ 3일 + 영사확인 4 ~ 8일)  ",
  "doc:transcript:holder": "본인",
  "doc:transcript:issuer": "학교",
  "doc:transcript:detailDesc": "고등학교 또는 대학교 서류를 제출합니다. 대학교 재학 또는 졸업생이더라도 고등학교 서류도 같이 제출하면 좋습니다.",
  "doc:balance:detailDesc": "비자 발급용과 대학 제출용(30일)은 유효기간이 달라 같은 서류를 재사용할 수 없으니 따로 발급받으세요. \n만약 일정이 촉박하여 잔고증명서 기간을 어려울 경우 \"유학경비 예치확인서\"로 대체하여 제출할 수 있습니다.",
  "doc:balance:holder": "본인 또는 부모. 단 부모가 없을 경우 삼촌·지인 가능",
  "doc:balance:form": "원본",
  "doc:balance:translation": "한글 또는 영어가 아닐 경우 번역 및 공증 필요",
  "doc:balance:validity": "10일 (단, 대학 제출용은 유효 기간 30일)",
  "doc:balance:obtainDays": "베트남 은행: 당일발급",
  "doc:bankbook:name": "통장",
  "doc:bankbook:brief": "잔고증명서의 통장 또는 국내 송금증명서의 입금계좌 통장. ",
  "doc:bankbook:detailDesc": "양도받은 통장은 인정되지 않습니다.",
  "doc:parent-support:cond": "",
  "doc:parent-support:holder": "재정보증인",
  "doc:parent-support:name": "재정지원확인서",
  "doc:parent-support:brief": "대사관 또는 공증사무소 또는 유학센터에서 제공하는 양식.",
  "doc:parent-support:issuer": "재정보증인",
  "doc:bankbook:_hidden": "[\"obtainDays\",\"validity\"]",
  "doc:remittance:obtainDays": "당일",
  "doc:parent-support:translation": "한글 또는 영어가 아닐 경우 번역 및 공증 필요",
  "doc:parent-support:_hidden": "[\"notarization\",\"validity\",\"obtainDays\"]",
  "doc:parent-income:holder": "재정보증인",
  "doc:parent-income:name": "재정보증인 소득·재직 증빙",
  "doc:parent-income:cond": "",
  "doc:parent-income:detailDesc": "보증인 1명(잔고 명의 부모) 기준이 원칙. 재정이 빠듯하면 두 분 소득을 함께 내면 유리. 직장인 → 재직증명·급여내역(최근 3개월)·사회보험 / 사업자 → 사업자등록·납세증명 / 농민 → 소득확인서·부동산(레드북). 단 직장 종류와 상관없이 최대한 제출하는 것이 유리.",
  "doc:parent-income:form": "원본",
  "doc:parent-income:translation": "한글 또는 영어가 아닐 경우 번역 및 공증 필요 (사업자등록증·부가세 납부증명은 제외)",
  "doc:parent-income:_hidden": "[\"notarization\"]",
  "doc:parent-income:obtainDays": "다양함",
  "doc:guarantor-id:name": "재정보증인 신분증",
  "doc:guarantor-id:brief": "재정보증인의 신분증.",
  "doc:guarantor-id:cond": "",
  "doc:guarantor-id:holder": "재정보증인",
  "doc:guarantor-id:detailDesc": "찰국 정부에서 발급하는 신분증입니다. CCCD (증명서는 사용불가)",
  "doc:guarantor-id:issuer": "공안부 사회질서행정관리경",
  "doc:guarantor-id:_hidden": "[\"translation\",\"validity\"]",
  "doc:guarantor-id:obtainDays": "7일",
  "doc:cost-pledge:brief": "재정보증인이 유학 비용을 부담하는지 서약.",
  "doc:cost-pledge:detailDesc": "보통 입학지원서에 포함됩니다.",
  "doc:cost-pledge:holder": "재정보증인",
  "doc:cost-pledge:issuer": "재정보증인",
  "doc:remittance:holder": "재정보증인",
  "doc:bankbook:holder": "재정보증인",
  "dyn:balance:univ:excellent:metro": "면제",
  "dyn:balance:univ:excellent:nonmetro": "면제",
  "dyn:balance:hagwon:excellent:metro": "잔액 1,000만원 이상 ·  6개월 유지",
  "dyn:balance:hagwon:excellent:nonmetro": "잔액 800만원 이상 ·  6개월 유지",
  "dyn:balance:hagwon:certified:metro": "잔액 1,000만원 이상 · 6개월 유지",
  "dyn:balance:hagwon:certified:nonmetro": "잔액 800만원 이상 · 6개월 유지",
  "dyn:balance:univ:general:metro": "잔액 2,000만원 이상 · 3개월 유지",
  "dyn:balance:univ:general:nonmetro": "잔액 1,600만원 이상 · 3개월 유지",
  "dyn:balance:hagwon:general:metro": "유학경비 예치확인서 제출",
  "doc:cost-pledge:_hidden": "[\"validity\"]",
  "doc:deposit-confirm:brief": "은행에 금액을 예치한 뒤 발급받는 서류",
  "dyn:balance:hagwon:general:nonmetro": "유학경비 예치확인서 제출",
  "doc:deposit-confirm:detailDesc": "비인증 어학당(D-4) 유학 시 잔고증명서 대신 제출합니다. 입국후 6개월 뒤 최대 50%, 12개월 뒤 잔액을 한국 은행으로 인출할 수 있습니다. ",
  "doc:training-plan:_hidden": "[\"obtainDays\",\"validity\"]",
  "doc:english:_hidden": "[\"obtainDays\"]",
  "doc:english:validity": "2년",
  "doc:korean:obtainDays": "2",
  "doc:korean:validity": "2년",
  "doc:korean:_hidden": "[\"obtainDays\"]",
  "doc:tb:obtainDays": "1일 ~ 7일",
  "doc:deposit-confirm:obtainDays": "예치일로부터 최대 3일",
  "doc:deposit-confirm:validity": "신청일로부터 30일 이내",
  "doc:parent-income:validity": "접수일로부터 30일 이내",
  "doc:remittance:validity": "10일",
  "doc:family-ct07:validity": "신청일로부터 3개월 이내",
  "doc:birth-cert:validity": "신청일로부터 3개월 이내",
  "doc:residence-ct08:validity": "신청일로부터 3개월 이내",
  "doc:residence-ct08:obtainDays": "1일 ~ 10일",
  "doc:grad-cert:validity": "신청일로부터 3개월 이내",
  "doc:transcript:validity": "신청일로부터 3개월 이내"
}'::jsonb),
  ('vi', '{
  "doc:passport:name": "Hộ chiếu",
  "doc:passport:brief": "Hộ chiếu nước sở tại",
  "doc:passport:detailDesc": "Hãy tìm hiểu kỹ quy trình cấp hộ chiếu và chuẩn bị trước.",
  "doc:passport:issuer": "Cục QLXNC Bộ Công an / Cục QLXNC công an địa phương",
  "doc:passport:validity": "Còn hạn ít nhất 6 tháng",
  "doc:passport:obtainDays": "Cục QLXNC Bộ Công an: 5 ngày / Cục QLXNC công an địa phương: 8 ngày",
  "doc:visa-form:name": "Đơn xin cấp visa",
  "doc:visa-form:brief": "Mẫu đơn của Đại sứ quán nộp khi xin visa",
  "doc:visa-form:detailDesc": "Cần 1 ảnh thẻ nền trắng 3.5×4.5cm (chụp trong vòng 6 tháng); có thể tải trước trên website Đại sứ quán.",
  "doc:id-card:name": "CCCD (Căn cước công dân)",
  "doc:id-card:brief": "CCCD của bản thân",
  "doc:id-card:detailDesc": "Là thẻ căn cước do chính phủ cấp. CCCD (không dùng giấy chứng nhận).",
  "doc:id-card:issuer": "Cục CSQLHC về TTXH - Bộ Công an",
  "doc:admission:name": "Giấy nhập học tiêu chuẩn",
  "doc:admission:brief": "Giấy xác nhận nhập học do trường đăng ký cấp.",
  "doc:admission:detailDesc": "Được cấp khi qua xét tuyển của trường, nộp khi Đại sứ quán thẩm định visa.",
  "doc:admission:obtainDays": "1 ~ 10 ngày kể từ ngày nộp hồ sơ",
  "doc:univ-reg:name": "Giấy phép kinh doanh của trường",
  "doc:univ-reg:brief": "Giấy tờ chính thức của Hàn Quốc do trường cung cấp",
  "doc:univ-reg:detailDesc": "Có thể xin từ trường; có thể thay bằng giấy chứng nhận mã số.",
  "doc:family-ct07:brief": "Giấy xác nhận thông tin cư trú.",
  "doc:family-ct07:detailDesc": "Xác nhận nơi cư trú của bản thân.",
  "doc:family-ct07:issuer": "Bộ Công an Việt Nam",
  "doc:family-ct07:signature": "Chỉ bản gốc ký tay (không chấp nhận điện tử·scan·in)",
  "doc:birth-cert:name": "Giấy khai sinh",
  "doc:birth-cert:brief": "Chứng minh quan hệ với cha mẹ.",
  "doc:birth-cert:detailDesc": "Xác nhận quốc tịch của cha mẹ và việc cha mẹ đúng là người bảo lãnh tài chính.",
  "doc:birth-cert:issuer": "Ủy ban nhân dân · Công an",
  "doc:residence-ct08:brief": "Nộp khi xin visa tại ĐSQ/LSQ khác nơi hộ khẩu",
  "doc:residence-ct08:detailDesc": "Có lịch sử cư trú từ 1 năm ở nơi khác hộ khẩu (thay thế: 6 tháng làm việc·học). Miễn nếu tốt nghiệp THPT trong vòng 6 tháng.",
  "doc:residence-ct08:issuer": "Công an Việt Nam",
  "doc:grad-cert:name": "Bằng tốt nghiệp",
  "doc:grad-cert:brief": "Bằng tốt nghiệp trường học cuối cùng.",
  "doc:grad-cert:detailDesc": "Nộp giấy tờ của THPT hoặc đại học. Nếu còn trong vòng 1 năm trước ngày dự kiến tốt nghiệp thì thay bằng giấy chứng nhận sẽ tốt nghiệp. Dù đang học hay đã tốt nghiệp đại học, nên nộp kèm cả giấy tờ THPT.",
  "doc:transcript:name": "Bảng điểm (học bạ)",
  "doc:transcript:brief": "Bảng điểm trường học cuối cùng.",
  "doc:transcript:detailDesc": "Nộp giấy tờ của THPT hoặc đại học. Dù đang học hay đã tốt nghiệp đại học, nên nộp kèm cả giấy tờ THPT.",
  "doc:balance:name": "Giấy xác nhận số dư tài khoản",
  "doc:balance:brief": "Chứng minh số dư tài khoản.",
  "doc:balance:detailDesc": "Bản nộp xin visa và bản nộp cho trường (30 ngày) có thời hạn khác nhau nên không thể dùng lại cùng một giấy, phải cấp riêng. \nNếu lịch trình gấp và khó đảm bảo thời hạn của giấy xác nhận số dư, có thể nộp thay bằng \"Giấy xác nhận ký quỹ chi phí du học\".",
  "doc:balance:holder": "Bản thân hoặc cha/mẹ. Nếu không có cha/mẹ thì có thể là chú/bác·người quen",
  "doc:balance:validity": "10 ngày (bản nộp cho trường: hiệu lực 30 ngày)",
  "doc:balance:obtainDays": "Ngân hàng Việt Nam: cấp trong ngày",
  "doc:bankbook:name": "Sổ tài khoản ngân hàng",
  "doc:bankbook:brief": "Sổ của giấy xác nhận số dư hoặc sổ tài khoản nhận tiền của giấy xác nhận chuyển tiền trong nước.",
  "doc:bankbook:detailDesc": "Sổ tài khoản được chuyển nhượng không được chấp nhận.",
  "doc:remittance:name": "Giấy xác nhận chuyển tiền vào Hàn Quốc",
  "doc:remittance:brief": "Khi chứng minh tài chính bằng cách chuyển tiền sang Hàn Quốc thay cho giấy xác nhận số dư.",
  "doc:parent-support:name": "Giấy bảo lãnh tài chính",
  "doc:parent-support:brief": "Mẫu do Đại sứ quán, văn phòng công chứng hoặc trung tâm du học cung cấp.",
  "doc:parent-income:name": "Chứng minh thu nhập · việc làm của người bảo lãnh",
  "doc:parent-income:brief": "Chuẩn bị theo nghề nghiệp của cha/mẹ đứng tên số dư.",
  "doc:parent-income:detailDesc": "Nguyên tắc theo 1 người bảo lãnh (cha/mẹ đứng tên số dư). Nếu tài chính eo hẹp, nộp thu nhập của cả hai sẽ có lợi. Người đi làm → giấy xác nhận công tác·bảng lương (3 tháng gần nhất)·bảo hiểm xã hội / Chủ kinh doanh → đăng ký kinh doanh·chứng từ nộp thuế / Nông dân → giấy xác nhận thu nhập·bất động sản (sổ đỏ). Dù nghề gì, nộp càng nhiều càng có lợi.",
  "doc:parent-income:issuer": "Công ty · thuế · công an, v.v.",
  "doc:guarantor-id:name": "CCCD của người bảo lãnh tài chính",
  "doc:guarantor-id:brief": "CCCD của người bảo lãnh tài chính.",
  "doc:guarantor-id:detailDesc": "Là thẻ căn cước do chính phủ cấp. CCCD (không dùng giấy chứng nhận).",
  "doc:guarantor-id:issuer": "Cục CSQLHC về TTXH - Bộ Công an",
  "doc:cost-pledge:name": "Cam kết chi trả chi phí du học",
  "doc:cost-pledge:brief": "Cam kết người bảo lãnh chi trả chi phí du học.",
  "doc:cost-pledge:detailDesc": "Thường được bao gồm trong đơn xin nhập học.",
  "doc:deposit-confirm:name": "Giấy xác nhận ký quỹ chi phí du học",
  "doc:deposit-confirm:brief": "Giấy tờ được cấp sau khi ký quỹ tiền tại ngân hàng",
  "doc:deposit-confirm:detailDesc": "Nộp thay cho giấy xác nhận số dư khi du học tại trung tâm tiếng chưa chứng nhận (D-4). Sau khi nhập cảnh 6 tháng có thể rút tối đa 50%, sau 12 tháng có thể rút số dư còn lại về ngân hàng Hàn Quốc.",
  "doc:deposit-confirm:issuer": "Ngân hàng · cơ quan chỉ định",
  "doc:tb:name": "Giấy khám lao (X-quang phổi)",
  "doc:tb:brief": "Cấp tại bệnh viện do cơ quan đại diện chỉ định.",
  "doc:tb:detailDesc": "Bao gồm chụp X-quang ngực. Danh sách bệnh viện chỉ định khác nhau theo cơ quan đại diện.",
  "doc:tb:issuer": "Bệnh viện do cơ quan đại diện chỉ định",
  "doc:tb:validity": "Trong vòng 3 tháng gần nhất",
  "doc:korean:name": "Chứng chỉ tiếng Hàn (TOPIK, v.v.)",
  "doc:korean:brief": "Khi đăng ký chương trình tiếng Hàn.",
  "doc:korean:cond": "Học vị: từ cử nhân TOPIK cấp 4 · cao đẳng cấp 3 / Trung tâm tiếng: theo tiêu chuẩn nhập học. Trường chứng nhận: khuyến khích, trường thường: bắt buộc.",
  "doc:korean:detailDesc": "Có thể thay bằng chứng chỉ KIIP·Sejong (Sejong chỉ công nhận khóa offline tại địa phương, không tính online).",
  "doc:korean:issuer": "Tổ chức khảo thí (TOPIK, v.v.)",
  "doc:training-plan:name": "Kế hoạch học tập",
  "doc:training-plan:brief": "Khi đăng ký trung tâm tiếng Hàn.",
  "doc:training-plan:detailDesc": "Bao gồm nội dung đào tạo: thời khóa biểu · giảng viên · cơ sở vật chất.",
  "doc:training-plan:holder": "Trường · cơ quan đào tạo",
  "doc:training-plan:issuer": "Trường · cơ quan đào tạo",
  "doc:english:name": "Chứng chỉ tiếng Anh",
  "doc:english:brief": "Khi đăng ký chương trình giảng dạy bằng tiếng Anh.",
  "doc:english:cond": "TOEFL 530 (iBT 71) / IELTS 5.5 / CEFR B2 / TEPS 327 trở lên.",
  "doc:english:issuer": "Tổ chức khảo thí",

  "dyn:balance:univ:excellent:metro": "Miễn",
  "dyn:balance:univ:excellent:nonmetro": "Miễn",
  "dyn:balance:univ:certified:metro": "Số dư từ 20 triệu won trở lên · duy trì 3 tháng",
  "dyn:balance:univ:certified:nonmetro": "Số dư từ 16 triệu won trở lên · duy trì 3 tháng",
  "dyn:balance:univ:general:metro": "Số dư từ 20 triệu won trở lên · duy trì 3 tháng",
  "dyn:balance:univ:general:nonmetro": "Số dư từ 16 triệu won trở lên · duy trì 3 tháng",
  "dyn:balance:hagwon:excellent:metro": "Số dư từ 10 triệu won trở lên · duy trì 6 tháng",
  "dyn:balance:hagwon:excellent:nonmetro": "Số dư từ 8 triệu won trở lên · duy trì 6 tháng",
  "dyn:balance:hagwon:certified:metro": "Số dư từ 10 triệu won trở lên · duy trì 6 tháng",
  "dyn:balance:hagwon:certified:nonmetro": "Số dư từ 8 triệu won trở lên · duy trì 6 tháng",
  "dyn:balance:hagwon:general:metro": "Nộp Giấy xác nhận ký quỹ chi phí du học",
  "dyn:balance:hagwon:general:nonmetro": "Nộp Giấy xác nhận ký quỹ chi phí du học",
  "dyn:deposit-confirm:metro": "Ký quỹ từ 10 triệu won trở lên",
  "dyn:deposit-confirm:nonmetro": "Ký quỹ từ 8 triệu won trở lên"
}'::jsonb)
on conflict (lang) do nothing;
