"""
batch_NNN_response.json 파일들 → UPDATE SQL 통합.

사용법:
    python scripts/cbt_batch_to_sql.py scripts/cbt_batches \\
        --out supabase/migrations/0013_cbt_ai_all.sql

각 batch_NNN_response.json 은 다음 형식:
[
  {"id": 1740, "intent_ko": "...", "intent_vi": "...",
   "choice_explanations": {"ko": {"1": "..."}, "vi": {"1": "..."}},
   "key_terms": [{"term_ko": "...", "def_vi": "..."}]},
  ...
]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def sql_str(s):
    if s is None:
        return "NULL"
    return "'" + str(s).replace("\\", "\\\\").replace("'", "''") + "'"


def sql_jsonb(obj):
    if obj is None:
        return "NULL"
    return (
        "'"
        + json.dumps(obj, ensure_ascii=False).replace("'", "''")
        + "'::jsonb"
    )


def normalize_explanations(ce):
    """{"ko": {1: ..}, "vi": {1: ..}} — 키 순서 정렬 + 빈 값 제거."""
    if not ce or not isinstance(ce, dict):
        return None
    ko = ce.get("ko") or {}
    vi = ce.get("vi") or {}

    def clean(d):
        if not isinstance(d, dict):
            return {}
        out = {}
        for k in sorted(d.keys(), key=lambda x: int(x) if str(x).isdigit() else 99):
            v = d.get(k)
            if isinstance(v, str) and v.strip():
                out[str(k)] = v.strip()
        return out

    ko_c = clean(ko)
    vi_c = clean(vi)
    if not ko_c and not vi_c:
        return None
    return {"ko": ko_c, "vi": vi_c}


def normalize_key_terms(terms):
    if not terms or not isinstance(terms, list):
        return None
    out = []
    for t in terms:
        if not isinstance(t, dict):
            continue
        term_ko = (t.get("term_ko") or "").strip()
        def_vi = (t.get("def_vi") or "").strip()
        if term_ko and def_vi:
            out.append({"term_ko": term_ko, "def_vi": def_vi})
    return out or None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("batches_dir")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    batches_dir = Path(args.batches_dir)
    response_files = sorted(batches_dir.glob("batch_*_response.json"))
    if not response_files:
        print(f"⚠️ {batches_dir} 에서 batch_*_response.json 찾지 못함", file=sys.stderr)
        sys.exit(1)

    print(f"발견된 응답 파일: {len(response_files)}", file=sys.stderr)

    all_results = {}
    for path in response_files:
        try:
            with path.open(encoding="utf-8") as f:
                arr = json.load(f)
        except Exception as e:
            print(f"  ⚠ {path.name} 파싱 실패: {e}", file=sys.stderr)
            continue
        if not isinstance(arr, list):
            print(f"  ⚠ {path.name} array 가 아님 — skip", file=sys.stderr)
            continue
        for item in arr:
            if not isinstance(item, dict):
                continue
            qid = item.get("id")
            if qid is None:
                continue
            all_results[int(qid)] = item

    print(f"통합된 row: {len(all_results)}", file=sys.stderr)

    out_path = Path(args.out)
    with out_path.open("w", encoding="utf-8") as out:
        out.write("-- =============================================================================\n")
        out.write("-- 0013_cbt_ai_all.sql (auto-generated by cbt_batch_to_sql.py)\n")
        out.write(f"-- {len(all_results)} rows\n")
        out.write("-- =============================================================================\n\n")

        for qid in sorted(all_results.keys(), reverse=True):
            ai = all_results[qid]
            intent_ko = ai.get("intent_ko")
            intent_vi = ai.get("intent_vi")
            ce = normalize_explanations(ai.get("choice_explanations"))
            kt = normalize_key_terms(ai.get("key_terms"))

            out.write(
                f"update public.cbt_questions set "
                f"intent_ko = {sql_str(intent_ko)}, "
                f"intent_vi = {sql_str(intent_vi)}, "
                f"choice_explanations = {sql_jsonb(ce)}, "
                f"key_terms = {sql_jsonb(kt)} "
                f"where id = {qid};\n"
            )

    print(f"\n✅ SQL: {out_path}", file=sys.stderr)
    print(f"   {len(all_results)} UPDATE 문 생성", file=sys.stderr)


if __name__ == "__main__":
    main()
